export const SET_TOKEN = 'SET_TOKEN';
export const SET_CURRENT_ID = 'SET_CURRENT_ID';
export const SET_PHOTOWALK = 'SET_PHOTOWALK';
export const SET_SELECTED_CHALLENGE = 'SET_SELECTED_CHALLENGE';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_PROFILEPICTURE = 'SET_PROFILEPICTURE';
export const SET_DRAWER = 'SET_DRAWER';
